// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    shim: {
      "d3": {
        exports: "d3"
      }
    },
    paths: {
      "d3": "//d3js.org/d3.v3.min"
    }
  });

  require(["d3", "vis/major-categories"], function(d3, MajorCategories) {
    return new MajorCategories(d3.select("#major-categories"));
  });

}).call(this);
