// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    shim: {
      "d3": {
        exports: "d3"
      }
    },
    paths: {
      "d3": "//d3js.org/d3.v3.min",
      "jquery": "//code.jquery.com/jquery-1.9.1.min"
    }
  });

  require(["d3", "vis/major-categories", "jquery"], function(d3, MajorCategories, $) {
    var fixedTop, lastScrollBottom, majors;
    majors = new MajorCategories($("#svg-holder"));
    fixedTop = 410;
    lastScrollBottom = 0;
    $(window).on("scroll", function() {
      var scrollBottom, scrollTop;
      scrollTop = $(window).scrollTop();
      if (scrollTop < 410) {
        majors.setPosition(null, 410 - $(window).scrollTop());
      } else {
        majors.setPosition(null, 0);
      }
      scrollBottom = $(window).height() + $(window).scrollTop();
      if (scrollBottom >= 800 && scrollBottom <= 1330) {
        majors.show();
      } else if (scrollBottom < 800 && lastScrollBottom >= 800) {
        majors.hide();
      } else if (scrollBottom > 1330 && lastScrollBottom <= 1330) {
        majors.hide("up");
      }
      return lastScrollBottom = scrollBottom;
    });
    return $(window).trigger("scroll");
  });

}).call(this);
